### ISSUE TITLE
Make repo layout a first class parameter

### ISSUE THREAD

**Issue by gregswift** [quadewarren/ansible-role-artifactory#5]
Right now it has to be passed through as a repo_config or repo_config_dict, but its actually kinda important. would probaby be good to default to `simple-default`, or maybe even do a basic opinionated mapping based on the known types (that would be fancy magic.. too bad artifactory doesnt already do that.. i mean why would you?)

**Comment by quadewarren** [comment]
I can add repoLayoutRef as a top-level parameter to this module, but I can't set any default value. It only references existing layouts, so if the layout doesn't exist, Artifactory will throw a 404 for the layout reference.

I could add some fancy magic so that the module will search for a default layout and if it does not find it, it will just not update that value, but that could add a lot of functionality to the code with little gain beyond "I don't have to define a default manually". There are pre-defined layouts, but they are specific to certain packageType's.

https://www.jfrog.com/confluence/display/RTF/Repository+Layouts#RepositoryLayouts-BundledLayouts
